ProyectoFinal/Controllers/EmpleadosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoFinal.Models;

namespace ProyectoFinal.Controllers
{
    public class EmpleadosController : Controller
    {
        private RecursosHumanosEntities4 db = new RecursosHumanosEntities4();

        // GET: Empleados
        public ActionResult Index()
        {
            var empleados = db.Empleados.Include(e => e.Cargo).Include(e => e.Departamento);
            return View(empleados.ToList());
        }

        // GET: Empleados/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleados empleados = db.Empleados.Find(id);
            if (empleados == null)
            {
                return HttpNotFound();
            }
            return View(empleados);
        }

        // GET: Empleados/Create
        public ActionResult Create()
        {
            ViewBag.IDCargo = new SelectList(db.Cargo, "IDCar", "NomCargo");
            ViewBag.IDDepartamento = new SelectList(db.Departamento, "IDDep", "IDDep");
            return View();
        }

        // POST: Empleados/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Cedula,Nombre,Apellido,Telefono,Email,IDDepartamento,IDCargo,FechaIng,Salario")] Empleados empleados)
        {
            if (ModelState.IsValid)
            {
                db.Empleados.Add(empleados);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IDCargo = new SelectList(db.Cargo, "IDCar", "NomCargo", empleados.IDCargo);
            ViewBag.IDDepartamento = new SelectList(db.Departamento, "IDDep", "IDDep", empleados.IDDepartamento);
            return View(empleados);
        }

        // GET: Empleados/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleados empleados = db.Empleados.Find(id);
            if (empleados == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDCargo = new SelectList(db.Cargo, "IDCar", "NomCargo", empleados.IDCargo);
            ViewBag.IDDepartamento = new SelectList(db.Departamento, "IDDep", "IDDep", empleados.IDDepartamento);
            return View(empleados);
        }

        // POST: Empleados/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Cedula,Nombre,Apellido,Telefono,Email,IDDepartamento,IDCargo,FechaIng,Salario")] Empleados empleados)
        {
            if (ModelState.IsValid)
            {
                db.Entry(empleados).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IDCargo = new SelectList(db.Cargo, "IDCar", "NomCargo", empleados.IDCargo);
            ViewBag.IDDepartamento = new SelectList(db.Departamento, "IDDep", "IDDep", empleados.IDDepartamento);
            return View(empleados);
        }

        // GET: Empleados/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleados empleados = db.Empleados.Find(id);
            if (empleados == null)
            {
                return HttpNotFound();
            }
            return View(empleados);
        }

        // POST: Empleados/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Empleados empleados = db.Empleados.Find(id);
            db.Empleados.Remove(empleados);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoFinal/Controllers/SumadoraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoFinal.Controllers
{
    public class SumadoraController : Controller
    {
        // GET: Sumadora
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(string Operacion, int num1, int num2)
        {
            int resultado;
            switch (Operacion)
            {
                case "+":
                    resultado = num1 + num2;
                    ViewBag.resultado = resultado;
                    break;
                case "-":
                    resultado = num1 - num2;
                    ViewBag.resultado = resultado;
                    break;
                case "x":
                    resultado = num1 * num2;
                    ViewBag.resultado = resultado;
                    break;
                case "/":
                    resultado = num1 / num2;
                    ViewBag.resultado = resultado;
                    break;

            }
            return View();
        }
        [HttpGet]
        public ActionResult CalcularTemperatura()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CalcularTemperatura(string Convertir, double valor)
        {
            double result;
            switch (Convertir)
            {
                case "Farenheit":
                    result = (valor * 1.8) + 32;
                    ViewBag.result = result;
                    break;
                case "Celsius":
                    result = (valor - 32)/ 1.8;
                    ViewBag.result = result;
                    break;
            }
            return View();
        }
        [HttpGet]
        public ActionResult CalcularMoneda()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CalcularMoneda(string Conversor, double valor)
        {
            double resultado;
            switch (Conversor)
            {
                case "Dolares":
                    resultado = 58.61 * valor;
                    ViewBag.resultado = resultado;
                    break;
                case "Peso":
                    resultado = 0.017 * valor;
                    ViewBag.resultado = resultado;
                    break;
            }
            return View();
        }
    }
}

ProyectoFinal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@1,600&family=Noto+Serif+JP:wght@500&display=swap" rel="stylesheet">
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <link href="~/Diseño/Estilos.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Recursos Humanos", "Index", "Empleados", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @Html.ActionLink("Nomina", "Listar", "Nomina", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("Operaciones", "Index", "Sumadora", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("Temperatura", "CalcularTemperatura", "Sumadora", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("Moneda", "CalcularMoneda", "Sumadora", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("Cargo", "Index", "Cargo", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("Departamento", "Index", "Departamento", new { area = "" }, new { @class = "navbar-brand" })
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>